version: '3.0'
services:
  streetmerchant:
    image: 035151873991.dkr.ecr.us-east-1.amazonaws.com/streetmerchant:latest
    container_name: streetmerchant
    restart: unless-stopped
    env_file:
      - dotenv
